### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by nncl** [nncl/node-socket-app#1]
- [ ] Broadcast a message to connected users when someone connects or disconnects
- [ ] Add support for nicknames
- [ ] Don’t send the same message to the user that sent it himself. Instead, append the message directly as soon as he presses enter.
- [ ] Add “{user} is typing” functionality
- [ ] Show who’s online
- [ ] Add private messaging

From  [Homework](http://socket.io/get-started/chat/) :)
